export default {
  grp_id: 0,
  org_id: 0,
  dep_id: 0,
  usr_id: '',
  emp_id: '',
  emp_name: '',
  emp_img: '',
  form_name: '',
  form_code: '',
  task_name: '',
  task_code: '',
  task_employee: 0,
  forms: [],
  activeField: [],
  activeTabForFields: 'elements',
  submit: false,
  form_url: '/pages/form_builder/form/',
  form_data_url: '/pages/form_builder/form-data/',
  form_stg_url: '/pages/form_builder/form-stage/',
  form_comment: '/pages/form_builder/form-comment/',
  form_upload: '/pages/form_builder/form-upload/',
};
